INSERT INTO `departments` (`id`, `code`, `name`, `codeISO`) VALUES
(null, '05', 'ANTIOQUIA', 'ANT'),
(null, '08', 'ATLANTICO', 'ATL'),
(null, '11', 'BOGOTA', 'DC'),
(null, '13', 'BOLIVAR', 'BOL'),
(null, '15', 'BOYACA', 'BOY'),
(null, '17', 'CALDAS', 'CAL'),
(null, '18', 'CAQUETA', 'CAQ'),
(null, '19', 'CAUCA', 'CAU'),
(null, '20', 'CESAR', 'CES'),
(null, '23', 'CORDOBA', 'COR'),
(null, '25', 'CUNDINAMARCA', 'CUN'),
(null, '27', 'CHOCO', 'CHO'),
(null, '41', 'HUILA', 'HUI'),
(null, '44', 'LA GUAJIRA', 'LAG'),
(null, '47', 'MAGDALENA', 'MAG'),
(null, '50', 'META', 'MET'),
(null, '52', 'NARIÑO', 'NAR'),
(null, '54', 'NORTE DE SANTANDER', 'NSA'),
(null, '63', 'QUINDIO', 'QUI'),
(null, '66', 'RISARALDA', 'RIS'),
(null, '68', 'SANTANDER', 'SAN'),
(null, '70', 'SUCRE', 'SUC'),
(null, '73', 'TOLIMA', 'TOL'),
(null, '76', 'VALLE DEL CAUCA', 'VAC'),
(null, '81', 'ARAUCA', 'ARA'),
(null, '85', 'CASANARE', 'CAS'),
(null, '86', 'PUTUMAYO', 'PUT'),
(null, '88', 'SAN ANDRES Y PROVIDENCIA', 'SAP'),
(null, '91', 'AMAZONAS', 'AMA'),
(null, '94', 'GUAINIA', 'GUA'),
(null, '95', 'GUAVIARE', 'GUV'),
(null, '97', 'VAUPES', 'VAU'),
(null, '99', 'VICHADA', 'VID');
